export default {
  经营收入: [
    {
      key: 'OFFICE_JYSR_ZJSR',
      title: '租金收入',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYSR_WYF',
      title: '物业费',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYSR_TCF',
      title: '停车费',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYSR_GGF',
      title: '广告费',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYSR_QTSR',
      title: '其他收入',
      after: '元',
    },
  ],
  经营成本: [
    {
      key: 'OFFICE_JYCB_YYCB',
      title: '营业成本',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYCB_TGCB',
      title: '推广成本',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYCB_RGCB',
      title: '人工成本',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYCB_GZCB',
      title: '改造成本',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_JYCB_QTCB',
      title: '其他成本',
      after: '元',
    },
  ],
  EBLTDA: [
    {
      key: 'SELECT_EBITDA_FLAG',
      title: '直接输入EBITDA',
      initialValue: '1',
      editData: [{ id: '1', value: '是' }, { id: '0', value: '否' }],
      type: '_radio',
    },
    {
      key: 'OFFICE_LR_EBITDA',
      title: 'EBLTDA',
      after: '元',
      type: 'radioInput',
      isEBLTDA: '1',
    },
    {
      key: 'OFFICE_JYCB_ZCGLFJZSYJ',
      title: '资产管理费及招商佣金',
      span: 12,
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
    },
    {
      key: 'OFFICE_JYCB_GYJZBDSY',
      title: '公允价值变动损益',
      span: 12,
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
    },
    {
      key: 'OFFICE_JYSR_YYWSR',
      title: '营业外收入',
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
    },
  ],
  租约情况: [
    {
      key: 'OFFICE_ZYQK_CZL',
      title: '出租率',
      after: '%',
    },
    {
      key: 'OFFICE_ZYQK_DYQYZMJ',
      title: '当月签约总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_DYQYZJZE',
      title: '当月签约租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZYQK_YQYZMJ',
      title: '已签约总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_YQYZJZE',
      title: '已签约租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZYQK_ZLZHZMJ',
      title: '主力租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_ZLZHZJZE',
      title: '主力租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZYQK_YNDQZHZMJ',
      title: '一年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_YNDQZHZJZE',
      title: '一年内到期租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZYQK_LNDQZHZMJ',
      title: '二年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_LNDQZHZJZE',
      title: '二年内到期租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZYQK_SNDQZHZMJ',
      title: '三年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'OFFICE_ZYQK_SNDQZHZJZE',
      title: '三年内到期租户租金总额',
      span: 12,
      after: '元',
    },
  ],
  租金情况: [
    {
      key: 'OFFICE_ZJQK_ZJSJZE',
      title: '租金收缴总额',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZJQK_PJZJ',
      title: '平均租金',
      span: 12,
      after: '元',
    },
    {
      key: 'OFFICE_ZJQK_ZJSJL',
      title: '租金收缴率',
      after: '%',
      span: 12,
    },
    {
      key: 'OFFICE_ZJQK_ZJZZL',
      title: '租金增长率',
      after: '%',
      span: 12,
    },
  ],
  其他: [
    {
      key: 'OFFICE_QT_RJGLMJ',
      title: '人均管理面积',
      after: '㎡',
    },
  ],
};
