export default {
  经营收入: [
    {
      key: 'PARK_JYSR_ZJSR',
      title: '租金收入',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYSR_WYF',
      title: '物业费',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYSR_TCF',
      title: '停车费',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYSR_GGSR',
      title: '广告费',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYSR_QTSR',
      title: '其他收入',
      after: '元',
    },
  ],
  经营成本: [
    {
      key: 'PARK_JYCB_RGCB',
      title: '人工成本',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYCB_TGSBWHF',
      title: '推广设备维护费',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_JYCB_QTCB',
      title: '其他成本',
      after: '元',
    },
  ],
  EBLTDA: [
    {
      key: 'SELECT_EBITDA_FLAG',
      title: '直接输入EBITDA',
      initialValue: '1',
      editData: [{ id: '1', value: '是' }, { id: '0', value: '否' }],
      type: '_radio',
    },
    {
      key: 'PARK_LR_EBITDA',
      title: 'EBLTDA',
      after: '元',
      type: 'radioInput',
      isEBLTDA: '1',
      rules: [{ required: false }],
    },
    {
      key: 'PARK_JYCB_ZCGLFJZSYJ',
      title: '资产管理费及招商佣金',
      span: 12,
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
      rules: [{ required: false }],
    },
    {
      key: 'PARK_JYCB_GYJZBDSY',
      title: '公允价值变动损益',
      span: 12,
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
      rules: [{ required: false }],
    },
    {
      key: 'PARK_JYSR_YYWSR',
      title: '营业外收入',
      after: '元',
      type: 'radioInput',
      isEBLTDA: '0',
      rules: [{ required: false }],
    },
  ],
  租约情况: [
    {
      key: 'PARK_ZYQK_CZL',
      title: '出租率',
      after: '%',
    },
    {
      key: 'PARK_ZYQK_DYQYZMJ',
      title: '当月签约总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_DYQYZJZE',
      title: '当月签约租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_YQYZMJ',
      title: '已签约总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_YQYZJZE',
      title: '已签约租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_ZLZHZMJ',
      title: '主力租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_ZLZHZJZE',
      title: '主力租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_BZXZHZMJ',
      title: '标准型租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_BZXZHZJZE',
      title: '标准型租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_YNDQZHZMJ',
      title: '一年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_YNDQZHZJZE',
      title: '一年内到期租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_LNDQZHZMJ',
      title: '二年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_LNDQZHZJZE',
      title: '二年内到期租户租金总额',
      span: 12,
      after: '元',
    },
    {
      key: 'PARK_ZYQK_SNDQZHZMJ',
      title: '三年内到期租户总面积',
      span: 12,
      after: '㎡',
    },
    {
      key: 'PARK_ZYQK_SNDQZHZJZE',
      title: '三年内到期租户租金总额',
      span: 12,
      after: '元',
    },
  ],
  租金情况: [
    {
      key: 'PARK_ZJQK_ZJSJZE',
      title: '租金收缴总额',
      after: '元',
    },
    {
      key: 'PARK_ZJQK_PJZJ',
      title: '平均租金',
      span: 12,
      after: '元/㎡·天',
    },
    {
      key: 'PARK_ZJQK_ZJSJL',
      title: '租金收缴率',
      span: 12,
      after: '%',
    },
  ],
};
